### ISSUE TITLE
Warning: Cookie names cannot contain any of the following '=,; \t\r\n\013\014' in [..]/Slim/Http/Response.php on line 292

### ISSUE THREAD

**Issue by phof** [slimphp/Slim#115]
Just updated to 1.3 and now getting:

`Warning: Cookie names cannot contain any of the following '=,; \t\r\n\013\014' in [..]/Slim/Http/Response.php on line 292`

**Comment by codeguy** [comment]
Can you attach a stack trace or an error log? Are you setting Cookies whose names contain those invalid characters?

**Comment by phof** [comment]
I get the error only every few page refreshes (ie, randomly), at times with the additional:

`Warning: Cannot modify header information - headers already sent by (output started at ../Slim/Http/Response.php:292) in ../Slim/Http/Response.php on line 292`

I'm not setting any cookies, the app is as simple as:

```
Slim::get('/', function () {
    Slim::render('index.php');
});

Slim::get('(/:a)/:b(/:c)/:d/', function ($a, $b, $c, $d) {
     Slim::render('result.php', array('a' => htmlspecialchars($a),
                                 'b' => htmlspecialchars($b),
                                 'c' => htmlspecialchars($c),
                                 'd' => htmlspecialchars($d)
                                ));
});
```

No log is created in the logs directory.

**Comment by codeguy** [comment]
Thanks for the code. Let me know if you can reliably duplicate the issue. Otherwise I'll use your code to try and duplicate the issue tomorrow. What environment are you using? (ie. Apache with mod_php, nginx + php_fpm, ...)

**Comment by phof** [comment]
I can reproduce the issue only every few page refreshes, the problem wasn't there on 1.2. I'm using Dreamhost shared hosting: Apache + PHP 5.3.5 via FastCGI.
Thank you for your help.

**Comment by codeguy** [comment]
Thanks. I'll be working on this issue this afternoon.

**Comment by codeguy** [comment]
@phollo Several things for you to try:
1. Initialize your Slim app using PHP's default session handler like this:
   
   Slim::init(array('session.handler' => null));
2. If the issue persists, comment out lines 361 and 377 in Slim/Slim.php

Let me know if either or both resolve the issue.

**Comment by codeguy** [comment]
Can you also provide the settings passed into `Slim::init()`?

**Comment by phof** [comment]
@codeguy Thank you for looking into this: `'session.handler' => null` seems to resolve the problem. I would have hoped to use the Slim session handler though, does that mean I won't be able to?

Before adding `'session.handler' => null` my Slim::init was:

```
Slim::init(array(
    'mode' => 'development'
));

Slim::configureMode('development', function () {
    Slim::config(array(
        'log.enable' => true,
        'log.path' => '../logs',
        'log.level' => 4,
        'debug' => true
    ));
});
```

Also, please note that no matter what `log.path` I indicate (and whether or not the dir exists or is writable), Slim doesn't seem to create logs.

**Comment by phof** [comment]
Please note I've used Slim 1.2 and sessions cookies for a different project on the same hosting provider with no issues.

**Comment by codeguy** [comment]
@phollo Can you confirm that using Slim's session handler while commenting out lines 361 and 377 in Slim/Slim.php did not work?

**Comment by codeguy** [comment]
@phollo Also can you create a dummy route like this:

```
Slim::get('/foo', function () { echo session_id(); });
```

Let me know what `session_id` generates, as that value is used as the name of the session cookie.

**Comment by codeguy** [comment]
Also, be sure you are not calling `session_start()` before `Slim::init`. Slim will start sessions for you.

**Comment by phof** [comment]
I can confirm that using Slim's session handler while commenting out lines 361 and 377 in Slim/Slim.php did not work: the random error re-appears.

The following are some example outputs from `Slim::get('/foo', function () { echo session_id(); });` with `'session.handler' => null`:

DR,ELMz964thoxdac8Hgh3
btWv,yWvaH8nNrCmob5P91
fsO3I1n6kcXuDhXuqeaRi1
5Tf42u0o5RfDYr0YIVKfF0
HZ8CDGgYMjo3-6RFtoL401
MGLR6UICTLFPo90Ei29vk0
fndvYm-hIRoo66PRyVDRU1
,2GUrLJlBnI-R,Hax09cF1

**Comment by phof** [comment]
Can also confirm I'm not calling `session_start()` at all.

**Comment by phof** [comment]
If the outputted values represent the cookies' names, those with the commas could be the ones causing the error. Hope it helps, please let me know if I can offer you further help with the debugging of this issue.

**Comment by codeguy** [comment]
Ok try adding this at the _very top_ of your bootstrap file.

```
ini_set('session.hash_bits_per_character', 4);
ini_set('session.hash_function', 0);
```

The first setting tells PHP to only use values 0-9,a-f for session IDs. The second tells PHP to use the md5 hashing algorithm to generate session IDs. You _should_ be able to just use the second one but I've provided both to be sure. Test out using just the second, then the first, then using both.

**Comment by codeguy** [comment]
Reference:

http://us2.php.net/manual/en/session.configuration.php#ini.session.hash-bits-per-character

**Comment by codeguy** [comment]
I've pushed 1.3.1 to master. Please compare your testing to that version. v1.3.1 _should_ resolve this issue by forcing session IDs to use only [a-z0-9] characters.

**Comment by phof** [comment]
- `ini_set('session.hash_function', 0);` doesn't work, still getting errors (strange as md5 should be ok?);
- `ini_set('session.hash_bits_per_character', 4);` works, no errors (0-9,a-f is good);
- they both work at the same time.

I see you included both lines in Slim.php 1.3.1; I can confirm that by just replacing the Slim directory from 1.3.1 the app throws no errors anymore.

@codeguy You're the man, thank you for your help!

**Comment by codeguy** [comment]
Great! Marking this as complete.
