### ISSUE TITLE
Cannot submit multipart/form-data using _METHOD

### ISSUE THREAD

**Issue by dccampbell** [slimphp/Slim#1372]
Since 3d2cac5, per #1277, createFromEnvironment constructs the Request object using the open `php://input` stream. It then checks if the request was from a form-urlencoded or form-data post, and if it is it returns the request with `$_POST` as it's body instead. This solves _'[php://input is not available with enctype="multipart/form-data".](http://php.net/manual/en/wrappers.php.php#wrappers.php.input)_'

However, submitting a file upload form (multipart/form-data) as a POST using a hidden _METHOD field to change the method type (to PUT usually) doesn't seem to work this way. It will always go through as a POST regardless.

I didn't have any luck solving this with my own middleware either. It almost seems like once the Request is constructed without the `$_POST` body it's too late to change for the sake of routing, although I haven't had a chance to dig in as to _why_. I had to add a fix to the bottom of Request's constructor to resolve it:

``` php
$this->registerMediaTypeParser('multipart/form-data', function() { return $_POST; });
```

**Comment by geggleto** [comment]
What version of slim is this for?

**Comment by dccampbell** [comment]
Slim 3.x, beta1 and latest.

**Comment by micheh** [comment]
Should be fixed now with #1393 if the original method is POST.

**Comment by micheh** [comment]
Should be fixed now with #1393 if the original method is POST.

**Comment by akrabat** [comment]
This doesn't solve the  'php://input is not available with enctype="multipart/form-data".' issue as file uploads also need to be handled when the method is a real PUT.

The latest 3.x does work with _METHOD = PUT though, so this issue is resolved.
