### ISSUE TITLE
develop branch: Twig view error

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#555]
Using the Slim skeleton app but with the develop branch, I get this error from the provided code.

```
Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 4096
Message: Argument 1 passed to Twig_Template::render() must be of the type array, object given, called in /Users/designermonkey/Sites/next-api.local/vendor/slim/extras/Slim/Extras/Views/Twig.php on line 99 and defined
File: /Users/designermonkey/Sites/next-api.local/vendor/twig/twig/lib/Twig/Template.php
Line: 244
Trace

#0 /Users/designermonkey/Sites/next-api.local/vendor/twig/twig/lib/Twig/Template.php(244): Slim\Slim::handleErrors(4096, 'Argument 1 pass...', '/Users/designer...', 244, Array)
#1 /Users/designermonkey/Sites/next-api.local/vendor/slim/extras/Slim/Extras/Views/Twig.php(99): Twig_Template->render(Object(Slim\Helper\Set))
#2 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/View.php(237): Slim\Extras\Views\Twig->render('index.html')
#3 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/View.php(227): Slim\View->fetch('index.html')
#4 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/Slim.php(734): Slim\View->display('index.html')
#5 /Users/designermonkey/Sites/next-api.local/public/index.php(40): Slim\Slim->render('index.html')
#6 [internal function]: {closure}()
#7 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#8 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/Slim.php(1294): Slim\Route->dispatch()
#9 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#12 /Users/designermonkey/Sites/next-api.local/vendor/slim/slim/Slim/Slim.php(1243): Slim\Middleware\PrettyExceptions->call()
#13 /Users/designermonkey/Sites/next-api.local/public/index.php(45): Slim\Slim->run()
#14 {main}
```

Thought this might be helpful before release.

**Comment by codeguy** [comment]
Thanks. I think the skeleton repo may be out of date... I'll look into it.

**Comment by codeguy** [comment]
This should be resolved by https://github.com/codeguy/Slim/issues/561 coming in 2.3.1 later this week.

**Comment by designermonkey** [comment]
Awesome, thanks Josh

**Comment by andrii-dymov** [comment]
I still have the same problem after change #561:

Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Code: 4096
Message: Argument 1 passed to Twig_Template::render() must be an array, object given, called in /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Extras/Views/Twig.php on line 99 and defined
File: /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Twig/lib/Twig/Template.php
Line: 244
Trace

#0 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Twig/lib/Twig/Template.php(244): Slim\Slim::handleErrors(4096, 'Argument 1 pass...', '/data01/virt392...', 244, Array)
#1 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Extras/Views/Twig.php(99): Twig_Template->render(Object(Slim\Helper\Set))
#2 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/View.php(252): Slim\Extras\Views\Twig->render('marine.html')
#3 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/View.php(242): Slim\View->fetch('marine.html')
#4 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Slim.php(742): Slim\View->display('marine.html')
#5 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/index.php(115): Slim\Slim->render('marine.html', Array)
#6 [internal function]: {closure}()
#7 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#8 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Slim.php(1302): Slim\Route->dispatch()
#9 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#12 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/Slim/Slim.php(1251): Slim\Middleware\PrettyExceptions->call()
#13 /data01/virt39293/domeenid/www.opms.com.au/htdocs/web-application/opms/index.php(159): Slim\Slim->run()
#14 {main}

**Comment by andrii-dymov** [comment]
Googling helped: must use the Twig view from the 'feature/no_static_views' branch of Extras.

**Comment by Sentence** [comment]
Yep, works with @awarche 's method, with latest Slim and Twig sources. Thanky.
